version: "3.7"
services:
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata/var/lib/postgresql/data
    ports:
      - 8081:8081
  api:
    image: henriqueleite-genoa-backend-test
    networks:
      - webnet
    depends_on:
      - db
    ports:
      - 8080:8080
networks:
  webnet:
